spring.application.name=NexOS

# PostgreSQL
spring.datasource.url=${DATA_BASE_URL}
spring.datasource.username=${DATA_BASE_USERNAME}
spring.datasource.password=${DATA_BASE_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true