CREATE TABLE tb_clientes (
    id_cliente BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_cliente VARCHAR(255),
    telefone_cliente VARCHAR(255),
    email_cliente VARCHAR(255)
);

CREATE TABLE tb_ordens_servico (
    id_ordem_servico BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente BIGINT NOT NULL,
    console VARCHAR(100) NOT NULL,
    defeito_relatado VARCHAR(1000) NOT NULL,
    analise_tecnico VARCHAR(2000),
    data_abertura TIMESTAMP NOT NULL,
    diagnostico VARCHAR(2000),
    valor NUMERIC(12, 2),
    custo_reparo NUMERIC(12, 2),
    status VARCHAR(30) NOT NULL,
    CONSTRAINT fk_ordens_servico_clientes
        FOREIGN KEY (id_cliente) REFERENCES tb_clientes (id_cliente)
);

CREATE INDEX idx_ordens_servico_cliente ON tb_ordens_servico (id_cliente);
CREATE INDEX idx_ordens_servico_status ON tb_ordens_servico (status);
CREATE INDEX idx_ordens_servico_data_abertura ON tb_ordens_servico (data_abertura);
