CREATE TABLE tb_historico_status_ordem_servico (
    id_historico BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_ordem_servico BIGINT NOT NULL,
    status_anterior VARCHAR(30) NOT NULL,
    status_novo VARCHAR(30) NOT NULL,
    data_alteracao TIMESTAMP NOT NULL,
    CONSTRAINT fk_historico_status_ordem_servico
        FOREIGN KEY (id_ordem_servico) REFERENCES tb_ordens_servico (id_ordem_servico)
);

CREATE INDEX idx_historico_status_ordem_servico_ordem
    ON tb_historico_status_ordem_servico (id_ordem_servico);
